### ISSUE TITLE
In UE 5.1, quitting the game while the stream is being received results in a crash

### ISSUE THREAD

**Issue by adrian-j-programmer** [millicast/millicast-player-unreal-engine-plugin#36] opened 2022-11-18 16:39 UTC
This does not occur when PIE is stopped, only when a standalone application is closed.

**Comment by dzeitman** [comment] 2022-11-18 19:59
@adrian-j-programmer  - Please expand a little deeper on this issue.   On the surface, it sounds like you may need to add methods to gracefully close the stream before closing the scene/level and or application.

**Comment by dbaldassi** [comment] 2022-11-21 08:19
I will investigate this today

**Comment by dbaldassi** [comment] 2022-11-22 08:21
I'm able to reproduce it. 
For the second call stack, when it crash in the in the OnFrame function, I can fix it by making a weak capture of this pointer to check if it is still valid.
For the first one, it just hangs and then crash, this might be some clean up issue in webrtc threads.

**Comment by dbaldassi** [comment] 2022-11-22 08:49
Seems that just adding a weak capture solves the issue. 
I've pushed it in e80d759

**Comment by dbaldassi** [comment] 2022-11-30 09:13
@adrian-j-programmer can you confirm this is solved for you ?

**Comment by adrian-j-programmer** [comment] 2022-11-30 16:30
The sync is still being lost over time. Interestingly enough, this time it's the video that is behind audio, not the other way around.

**Comment by dbaldassi** [comment] 2022-12-02 09:07
For both callstack, or only one now ?

**Comment by adrian-j-programmer** [comment] 2022-12-02 09:30
I'm only seeing this one now:
```
[REDACTED]!UMillicastSubscriberComponent::~UMillicastSubscriberComponent() [/project/Plugins/MillicastPlayer/Source/MillicastPlayer/Private/Components/MillicastSubscriberComponent.cpp:42]," [REDACTED]!UMillicastSubscriberComponent::~UMillicastSubscriberComponent() [/project/Plugins/MillicastPlayer/Source/MillicastPlayer/Private/Components/MillicastSubscriberComponent.cpp:42]"
2022-12-01T17:00:53.894Z,"0x0000000005bfc81a [REDACTED]!bool FAsyncPurge::TickDestroyObjects<false>(bool, float, double)()"," [REDACTED]!bool FAsyncPurge::TickDestroyObjects<false>(bool, float, double)()"
2022-12-01T17:00:53.894Z,"0x0000000005bfc11f [REDACTED]!FAsyncPurge::TickPurge(bool, float, double)()"," [REDACTED]!FAsyncPurge::TickPurge(bool, float, double)()"
2022-12-01T17:00:53.894Z,"0x0000000005bd5b86 [REDACTED]!IncrementalPurgeGarbage(bool, double)()"," [REDACTED]!IncrementalPurgeGarbage(bool, double)()"
```

**Comment by dbaldassi** [comment] 2022-12-06 08:24
Hi @adrian-j-programmer, I am not able to reproduce this crash on  my side. I have tried to run the packaged game in debug and shipping, in the editor in multiplayer and solo. 
My steps are : 
- Run the game
- Subscribe as soon as it launch
- leave it for a few seconds
- Close the game (making the unsubscribe call in the destructor)
If there are any missing steps to reproduce this please let me know.
Since I am not able to reproduce I will write useful debug logs to check what is going on in the unsubscribe function and try to understand what is causing the crash.
Also, can you make sure that you picked this commit ? 4000c6c4277e20f4b15565f8d0b7bfcdbe9b68a9

**Comment by adrian-j-programmer** [comment] 2022-12-06 17:41
We are using the patch commit already, just double-checked. 
I can't think of anything else you might wanna try here. It looks like it's not dependent on how long the client has been run (and millicast subscribed) before shutdown, so I'm not really sure what's going on... If you add in some logging, I'll integrate this change asap so we can get more data.

**Comment by dbaldassi** [comment] 2022-12-13 10:24
I have added logs the plugin, can you send me the log file corresponding to this issue ?

**Comment by adrian-j-programmer** [comment] 2023-01-05 15:46
Posting for visibility here.
The issue is caused by the destructor of the UMillicastSubscriberComponent calling the Unsubscribe method. Inside the Unsubscribe method, all cached media tracks are iterated through and cleared. This causes a crash if the destructor of the component was run as part of the garbage collection job. In this case, the tracks might have already been cleared by GC, so accessing their pointers leads to a crash.

**Comment by dbaldassi** [comment] 2023-01-09 08:31
Actually, the tracks have been added to root, so I don't think they are cleared by the GC before calling the RemoveToRoot method

**Comment by rweber89** [comment] 2023-02-13 17:41
@adrian-j-programmer could you please check if this is still an issue for you? There is a potential fix on the **dev** branch

**Closed** 2023-05-14 23:33 UTC
Labels: bug
