### ISSUE TITLE
Packaging Error 4.27 Millicast Version 1.4.0

### ISSUE THREAD

**Issue by MaxDorn96** [millicast/millicast-player-unreal-engine-plugin#20] opened 2022-08-18 12:01 UTC
By packaging a Linux Server I get the following error

Project\Plugins\Millicast\Source\MillicastPlayer\Private\WebRTC\AudioDeviceModule.cpp(7,35): error: copying variable of type 'TAtomic<bool>' invokes deleted constructor

We had already implemented Millicast in our Project before but I now updated the Plugin to the 1.4.0 Version.

I deleted Intermediate, Saved and Binaries Folders, generated Project files and build the Project from the IDE after getting the Plugin and everything seems fine, I can also use all Features in the Editor, only the Packages after the Updates fail at this point.

I hope you would be able to help me with this.

Later Edit:
My Company works with Linux Server and Windows Clients and Packaging for Windows Clients works just fine as is, so I don't quite know if this is a Linux only error

Also I also wanted to provide these lines which come right after the error:
C:\UE4_27_Source\Engine\Source\Runtime\Core\Public\Templates\Atomic.h(590,2): note: 'TAtomic' has been explicitly marked deleted here

TAtomic(TAtomic&&) = delete;

**Comment by adrian-j-programmer** [comment] 2022-08-19 13:45
I've spent a fair amount of time going through Linux compilation issues today, and discovered some more after having fixed this TAtomic initialization error locally. 

1. The plugin fails to link against the Opus library symbols
2, It also fails to link some of the webRTC symbols:
ld.lld: error: undefined symbol: webrtc::PeerConnectionInterface::IceServer::~IceServer()

These issues and the original post result in the plugin failing to compile on Linux. It's also possible there are some more issues after these 3 are resolved. 
Our team would appreciate this getting this hotfixed quickly.

**Comment by dbaldassi** [comment] 2022-08-31 07:34
Which version of Linux are you using ?
I just package a game on linux and did not get any error.
Which version of the plugin are you using ? Is there any extra steps I need to know to reproduce it ?

**Comment by dbaldassi** [comment] 2022-08-31 12:53
Actually, I was building with UE5, indeed in UE4 I got the Atomic compilation error.
It is fixed now.
However, I did not get any linking issue with opus.

**Comment by adrian-j-programmer** [comment] 2022-09-06 09:30
Hey, after pulling down this latest version we are still hitting the linking error as mentioned above. At this point we are wondering if it might have anything to do with the fact our application uses the PixelStreaming plugin. We don't see anything to indicate it would be an issue, because the Milicast plugin does not come with any precompiled libraries of its own, instead linking against the same libs the Pixel Streaming plugin does. 

Here's the build output with the linking errors listed. This is being built inside the official UE 4.27.2 docker container, so it's an easily reproducible environment. 

```
ld.lld: error: undefined symbol: opus_encoder_create
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_EncoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_encoder_destroy
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_EncoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_EncoderFree) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_encoder_destroy
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_EncoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_EncoderFree) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_MultistreamEncoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_encoder_create
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_MultistreamEncoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_encode
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_Encode) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_encode
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_Encode) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_encoder_ctl
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_SetBitRate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_SetPacketLossRate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_SetMaxPlaybackRate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced 16 more times
  
  ld.lld: error: undefined symbol: opus_multistream_encoder_ctl
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_SetBitRate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_SetPacketLossRate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_SetMaxPlaybackRate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced 14 more times
  
  ld.lld: error: undefined symbol: opus_decoder_create
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_decoder_destroy
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecoderFree) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_decoder_create
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_MultistreamDecoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_decoder_destroy
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_MultistreamDecoderCreate) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecoderFree) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_decoder_ctl
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecoderInit) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_decoder_ctl
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecoderInit) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_decode
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_Decode) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_Decode) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecodeFec) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_multistream_decode
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_Decode) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_Decode) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecodeFec) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_packet_get_samples_per_frame
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DecodeFec) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_PacketHasFec) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DurationEst) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  >>> referenced 1 more times
  
  ld.lld: error: undefined symbol: opus_packet_parse
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_PacketHasFec) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_packet_get_nb_channels
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_PacketHasFec) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  
  ld.lld: error: undefined symbol: opus_packet_get_nb_frames
  >>> referenced by opus_interface.cc
  >>>               opus_interface.o:(WebRtcOpus_DurationEst) in archive /home/ue4/UnrealEngine/Engine/Source/ThirdParty/WebRTC/4147/Lib/Linux/x86_64-unknown-linux-gnu/Release/libwebrtc.a
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dbaldassi** [comment] 2022-09-07 11:23
I could reproduce using the docker container.
I have added libOpus in the dependency, it works for me now.
commit 1bd27e9252329ab860edfc0a052fde888c6ea3f0

**Comment by adrian-j-programmer** [comment] 2022-09-07 14:14
Hey, this latest change does fix the plugin not compiling. Unfortunately, as soon as the plugin is used in gameplay code, it fails to link the webRTC symbols. Specifically, as soon as we implement a callback `UFUNCTION void OnAuthenticated(const FMillicastSignalingData& signalingData);`, the project no longer compiles. It fails to link with these errors listed in the build output:

`  ld.lld: error: undefined symbol: webrtc::PeerConnectionInterface::IceServer::~IceServer()
  >>> referenced by MemoryOps.h:183 (Runtime/Core/Public/Templates/MemoryOps.h:183)
  >>>               /project/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/[Redacted]/Module.[Redacted].gen.7_of_8.cpp.o:(AO_StreamScreen::execOnAuthenticated(UObject*, FFrame&, void*))
  >>> referenced by MemoryOps.h:183 (Runtime/Core/Public/Templates/MemoryOps.h:183)
  >>>               /project/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/[Redacted]/Module.[Redacted].gen.7_of_8.cpp.o:(AO_StreamScreen::execOnAuthenticated(UObject*, FFrame&, void*))`

Again, this all happens when building inside the official docker image. Please advise on the next steps to get it to work. We're more than happy to provide any additional info that might help you.

Thanks,
Adrian

**Comment by dbaldassi** [comment] 2022-09-07 15:41
Did you bind a callback in C++ or in the blueprint ?

**Comment by dbaldassi** [comment] 2022-09-07 16:18
I could reproduce your issue.
If you add "WebRTC" in the Dependency module names of your project it solves this linking issue.
I don't know why it is needed as WebRTC is listed as a public dependency in the plugin build file.
Also, this error seems to happen only with the docker image.

**Comment by adrian-j-programmer** [comment] 2022-09-09 08:44
I can confirm that our containerized project now compiles correctly. This ticket can be closed.

**Closed** 2022-09-09 12:32 UTC
